acom/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.contrib import admin
from django.urls import path, include
from .views import login,paynow_payment
urlpatterns = [
    path('admin/', admin.site.urls),
    path('rentals/', include('rental.urls')),
    path('api/login', login),
    path('api/paynow', paynow_payment),
    
    path('', include('iauth.urls')),
    path('rest_api/', include('api.urls')),
]

api/urls.py
from django.conf.urls import url
# from .import views
from .serializers import *
from .views import *
# urlpatterns = [
#     url(r'^$', views.index, name='index'),
# ]
# Routers provide an easy way of automatically determining the URL conf.
app_name = 'api'
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'profiles', ProfileViewSet)
router.register(r'rental_listings', RentalListingViewSet)
router.register(r'bookings', BookingViewSet)
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

iauth/urls.py
from django.urls import path
from .views import edit, dashboard, register, myprofile
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)

app_name = 'iauth'

urlpatterns = [
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('myprofile/', myprofile, name='myprofile'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='iauth/logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='iauth/password_change_form.html'), name='password_change'),
    path('password_change/dond/', PasswordChangeDoneView.as_view(template_name='iauth/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='iauth/password_reset_form.html',
        email_template_name='iauth/password_reset_email.html',
        success_url=reverse_lazy('iauth:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='iauth/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='iauth/password_reset_confirm.html',
        success_url=reverse_lazy('iauth:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='iauth/password_reset_complete.html'), name='password_reset_complete'),

]

rental/urls.py
from django.urls import path

from . import views
app_name = 'rental'
urlpatterns = [
    path('', views.index, name='index'),
    path('places', views.places, name='places'),
    path('add_place', views.add_place, name='add_place'),
    path('search', views.search, name='search'),
    path('place_booking', views.place_booking, name='place_booking'),
    path('my_booking', views.my_booking, name='my_booking'),
    path('pay_booking', views.pay_booking, name='pay_booking'),
    
]

iauth/models.py
from django.db import models

# Create your models here.
# from django.db import models
from django.conf import settings
# Create your models here.
from django.contrib.auth.models import User

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


class UserRegistrationModel(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

iauth/forms.py
from django.contrib.auth.models import User
from django import forms
from api.models import profile


class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = (
            'user',
            # 'bio','age','phone','current_address',
            'city',
            'gender',
            'nearby_institute',
            )

iauth/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

# Create your views here.
from django.http import request
# from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserRegistration, UserEditForm
from django.contrib.auth.models import User,Group
from rental.models import *
from api.models import *
from .forms import *
from django.http import HttpResponse
# Create your views here.
from django.db.models import Q

@login_required
def dashboard(request):
    my_places = []
    groups = request.user.groups.all()
    system_groups = Group.objects.all()
    # Entry.objects.filter(~Q(id=3))
    my_profile = profile.objects.get(user=request.user.id)
    rental_places = rental_listing.objects.filter(~Q(available_rooms=0),preference=my_profile.gender)

    my_bookings = Booking.objects.filter(tenant=my_profile)
    my_payments = BookingPay.objects.filter(payment_made_by=request.user)
    for group in groups:
        # print("Group XX")
        # print(group.name)
        if group.name == "Agent" or group.name == "Owner":
            my_places = rental_listing.objects.filter(home_owner=request.user.id)
        else:
            my_places = []
    context = {
        "my_payments":my_payments,
        "my_bookings":my_bookings,
        "rental_places":rental_places,
        "my_places": my_places,
        "system_groups":system_groups,
        "groups": groups,
        "welcome": "Welcome to your dashboard"
    }
    return render(request, 'iauth/dashboard.html', context=context)


@login_required
def myprofile(request):
    prof = profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = ProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            b4_Form = profile.objects.get(user=request.user)
            b4_Form.city = request.POST.get('city')
            b4_Form.nearby_institute = request.POST.get('nearby_institute')
            b4_Form.save() 
            # form.update()
            return HttpResponse("Data Saved Successfully")
        else:
            return HttpResponse("Form Is not valid")
    else:            
        profile_form = ProfileForm(instance=request.user)  
    groups = request.user.groups.all()
    context = {
        "prof":prof,
        "groups":groups,
        "profile_form": profile_form,
        "welcome": "Welcome to your profile"
    }
    return render(request, 'iauth/profile.html', context=context)



def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            return render(request, 'iauth/register_done.html')
    else:
        form = UserRegistration()

    context = {
        "form": form
    }

    return render(request, 'iauth/register.html', context=context)


@login_required
def edit(request):
    prof = ""
    system_groups = ""
    groups = request.user.groups.all()
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        mygrp= request.POST.get('my_grp')
        g = Group.objects.get(name=mygrp)
        u = request.user
        g.user_set.add(u)
        if user_form.is_valid():
            user_form.save()
    else:
        prof = request.GET['profile']
        system_groups = Group.objects.get(name=prof)
        user_form = UserEditForm(instance=request.user)
    context = {
        "system_groups":system_groups,
        "prof":prof,
        'form': user_form,
       "groups": groups,
    }
    return render(request, 'iauth/edit.html', context=context)

iauth/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome CDN -->

    <!-- chart -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/js/bootstrap.min.js" integrity="sha512-NWNl2ZLgVBoi6lTcMsHgCQyrZVFnSmcaa3zRv0L3aoGXshwoxkGs3esa9zwQHsChGRL4aLDnJjJJeP6MjPX46Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.0/chart.min.js" integrity="sha512-asxKqQghC1oBShyhiBwA+YgotaSYKxGP1rcSYTDrB0U6DxwlJjU59B67U8+5/++uFjcuVM8Hh5cokLjZlhm3Vg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'iauth/content/css/site.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'iauth/content/css/boot.css' %}">
    <style type="text/css">
        .scrollax-performance,
        .scrollax-performance *,
        .scrollax-performance *:before,
        .scrollax-performance *:after {
            pointer-events: none !important;
            -webkit-animation-play-state: paused !important;
            animation-play-state: paused !important;
        }
        
        ;
    </style>
    <script type="text/javascript" charset="UTF-8" src="{% static 'iauth/content/js/common.js' %}"></script>
    <script type="text/javascript" charset="UTF-8" src="{% static 'iauth/content/js/util.js' %}"></script>
    <title> {% block title %}{% endblock title %}</title>
</head>

<body data-aos-easing="slide" data-aos-duration="800" data-aos-delay="0">
    {% include "navbar.html" %}
    <div class="js-fullheight" style="background-image: url('{% static 'iauth/content/img/backg.jpg' %}'); height: 730px; background-position: 100%;" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            {% block content %} {% endblock content %}
        </div>
        {% include "footer.html" %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
    <script src="{% static 'iauth/content/js/main.js' %}"></script>
    <script src="{% static 'iauth/content/js/jquery-migrate-3.js' %}"></script>
    <script src="{% static 'iauth/content/js/jquery.easing.js' %}"></script>
    <script src="{% static 'iauth/content/js/jquery.me.js' %}"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js ', new Date());

        gtag('config ', 'UA-23581568-13 ');
    </script>
    <script defer="" src="{% static 'iauth/content/js/beacon.min.js'%}" data-cf-beacon="{&quot;rayId&quot;:&quot;6592526b2a1e0566&quot;,&quot;token&quot;:&quot;cd0b4b3a733644fc843ef0b185f98241&quot;,&quot;version&quot;:&quot;2021.5.2&quot;,&quot;si&quot;:10}"></script>

</body>

</html>

iauth/templates/footer.html
{% load static %}
<!-- <footer class="ftco-footer ftco-footer-2 ftco-section">

</footer> -->

iauth/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light scrolled awake" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand text-light" href="">Accom Finder <i class="fas fa-map"></i></a>
        <!-- <a class="navbar-brand" href=""><span>Knights</span></a> -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="/dashboard" class="nav-link">My Dashboard</a></li>
                <li class="nav-item active"><a href="{% url 'rental:index' %}" class="nav-link">Residential Locator</a></li>
                <li class="nav-item active"><a href="{% url 'rental:places' %}" class="nav-link">Residential Places</a></li>
                <li class="nav-item cta">
                    <a class="nav-link" href="{% url 'iauth:logout' %}"><i class="fas fa-lock"></i> Logout</a>
                </li>
                <li class="nav-item 1"><a href="{% url 'iauth:myprofile' %}" class="nav-link">@ <i>{{user.username}}</i></a></li>
                {% else %}
                <div class="login__left">
                    <a href="{% url 'iauth:login' %}" class="btn btn-secondary btn-sm ">Log-in</a>
                    <a href="{% url 'iauth:register' %}" class="btn btn-info btn-sm">Register</a>
                </div>
            </ul>
            {% endif %}

        </div>
    </div>
</nav>