acom/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.contrib import admin
from django.urls import path, include
from .views import login,paynow_payment
urlpatterns = [
    path('admin/', admin.site.urls),
    path('rentals/', include('rental.urls')),
    path('api/login', login),
    path('api/paynow', paynow_payment),
    
    path('', include('iauth.urls')),
    path('rest_api/', include('api.urls')),
]

api/urls.py
from django.conf.urls import url
# from .import views
from .serializers import *
from .views import *
# urlpatterns = [
#     url(r'^$', views.index, name='index'),
# ]
# Routers provide an easy way of automatically determining the URL conf.
app_name = 'api'
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'profiles', ProfileViewSet)
router.register(r'rental_listings', RentalListingViewSet)
router.register(r'bookings', BookingViewSet)
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

iauth/urls.py
from django.urls import path
from .views import edit, dashboard, register, myprofile
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)

app_name = 'iauth'

urlpatterns = [
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('myprofile/', myprofile, name='myprofile'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='iauth/logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='iauth/password_change_form.html'), name='password_change'),
    path('password_change/dond/', PasswordChangeDoneView.as_view(template_name='iauth/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='iauth/password_reset_form.html',
        email_template_name='iauth/password_reset_email.html',
        success_url=reverse_lazy('iauth:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='iauth/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='iauth/password_reset_confirm.html',
        success_url=reverse_lazy('iauth:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='iauth/password_reset_complete.html'), name='password_reset_complete'),

]

rental/urls.py
from django.urls import path

from . import views
app_name = 'rental'
urlpatterns = [
    path('', views.index, name='index'),
    path('places', views.places, name='places'),
    path('add_place', views.add_place, name='add_place'),
    path('search', views.search, name='search'),
    path('place_booking', views.place_booking, name='place_booking'),
    path('my_booking', views.my_booking, name='my_booking'),
    path('pay_booking', views.pay_booking, name='pay_booking'),
    
]

iauth/models.py
from django.db import models

# Create your models here.
# from django.db import models
from django.conf import settings
# Create your models here.
from django.contrib.auth.models import User

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


class UserRegistrationModel(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

iauth/forms.py
from django.contrib.auth.models import User
from django import forms
from api.models import profile


class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = (
            'user',
            # 'bio','age','phone','current_address',
            'city',
            'gender',
            'nearby_institute',
            )

iauth/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

# Create your views here.
from django.http import request
# from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserRegistration, UserEditForm
from django.contrib.auth.models import User,Group
from rental.models import *
from api.models import *
from .forms import *
from django.http import HttpResponse
# Create your views here.
from django.db.models import Q

@login_required
def dashboard(request):
    my_places = []
    groups = request.user.groups.all()
    system_groups = Group.objects.all()
    # Entry.objects.filter(~Q(id=3))
    my_profile = profile.objects.get(user=request.user.id)
    rental_places = rental_listing.objects.filter(~Q(available_rooms=0),preference=my_profile.gender)

    my_bookings = Booking.objects.filter(tenant=my_profile)
    my_payments = BookingPay.objects.filter(payment_made_by=request.user)
    for group in groups:
        # print("Group XX")
        # print(group.name)
        if group.name == "Agent" or group.name == "Owner":
            my_places = rental_listing.objects.filter(home_owner=request.user.id)
        else:
            my_places = []
    context = {
        "my_payments":my_payments,
        "my_bookings":my_bookings,
        "rental_places":rental_places,
        "my_places": my_places,
        "system_groups":system_groups,
        "groups": groups,
        "welcome": "Welcome to your dashboard"
    }
    return render(request, 'iauth/dashboard.html', context=context)


@login_required
def myprofile(request):
    prof = profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = ProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            b4_Form = profile.objects.get(user=request.user)
            b4_Form.city = request.POST.get('city')
            b4_Form.nearby_institute = request.POST.get('nearby_institute')
            b4_Form.save() 
            # form.update()
            return HttpResponse("Data Saved Successfully")
        else:
            return HttpResponse("Form Is not valid")
    else:            
        profile_form = ProfileForm(instance=request.user)  
    groups = request.user.groups.all()
    context = {
        "prof":prof,
        "groups":groups,
        "profile_form": profile_form,
        "welcome": "Welcome to your profile"
    }
    return render(request, 'iauth/profile.html', context=context)



def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            return render(request, 'iauth/register_done.html')
    else:
        form = UserRegistration()

    context = {
        "form": form
    }

    return render(request, 'iauth/register.html', context=context)


@login_required
def edit(request):
    prof = ""
    system_groups = ""
    groups = request.user.groups.all()
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        mygrp= request.POST.get('my_grp')
        g = Group.objects.get(name=mygrp)
        u = request.user
        g.user_set.add(u)
        if user_form.is_valid():
            user_form.save()
    else:
        prof = request.GET['profile']
        system_groups = Group.objects.get(name=prof)
        user_form = UserEditForm(instance=request.user)
    context = {
        "system_groups":system_groups,
        "prof":prof,
        'form': user_form,
       "groups": groups,
    }
    return render(request, 'iauth/edit.html', context=context)

iauth/templates/iauth/dashboard.html
 <!DOCTYPE html>{% extends "base.html" %} {% block title %}Dashboard{% endblock title %} {% block content %}
<div class="container bg-light">
    <hr/>
    <hr/>
    <hr/>
    <hr/>

    {% if groups %} 
    <!-- Welcome : -->
   {% if groups%}
    {% for group in groups %}
     <!-- {{ group.name }}  -->
     <hr/>
        {% if group.name == "Agent" or group.name == "Owner"%}
            <!-- <button onclick="getLocation()">Add this Current Location</button>
        <p id="demo"></p> -->
        <a href="{% url 'rental:add_place' %}" class="nav-link">Add Place</a>
        {% if my_places%}
            {% for place in my_places%}
                <div class="card" style="font-size:small">
                    <div class="card-body">
                    <table class="table table-info" style="font-size:x-small">
                        <tr>
                            <td colspan="1">Details : </td>
                            <td colspan="2">{{place.description}}</td>
                            <td colspan="1">Address : </td>
                            <td colspan="2">{{place.address}}</td>
                            <td colspan="1">Price : </td>
                            <td colspan="2">{{place.price_per_room}}</td>
                            <td colspan="1"><button class="btn btn-sm btn-info" style="font-size:x-small">Edit</button></td>
                        </tr>
                    </table>
                    <h5 class="card-title"></h5>
                    <p class="card-text"></p>
                    <p class="card-text"><small class="text-muted"></small></p>
                    <hr/>                    
                    </div>
                </div>
            {% endfor %}
        {% endif %}
       {% else %}
        
    <div class="container">
        <button class="btn btn-sm btn-primary" style="font-size:x-small">Look For A place</button>
<ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="Places-tab" data-bs-toggle="tab" data-bs-target="#Places" type="button" role="tab" aria-controls="Places" aria-selected="true">Places</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="Bookings-tab" data-bs-toggle="tab" data-bs-target="#Bookings" type="button" role="tab" aria-controls="Bookings" aria-selected="false">Bookings</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="Payments-tab" data-bs-toggle="tab" data-bs-target="#Payments" type="button" role="tab" aria-controls="Payments" aria-selected="false">Payments</button>
        </li>
        </ul>
        <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="Places" role="tabpanel" aria-labelledby="Places-tab">
            {% for place in rental_places %}
                <div class="card" style="font-size:small">
                    <div class="card-body">
                    <table class="table table-info" style="font-size:x-small">
                        <tr>
                            <td colspan="1">Details : </td>
                            <td colspan="2">{{place.description}}</td>
                            <td colspan="1">Address : </td>
                            <td colspan="2">{{place.address}}</td>
                            <td colspan="1">Price : </td>
                            <td colspan="2">{{place.price_per_room}}</td>
                            <td colspan="1">
                                <!-- place_booking -->
                                 <form method="post" action="{% url 'rental:place_booking' %}">
                                    {% csrf_token%}
                                    <input hidden value="{{place.id}}" id="id_rental" name="rental"/>
                                    <input class="btn btn-sm btn-info" style="font-size:x-small" type="submit" value="Book" />
                                </form>
                                <!-- <button class="btn btn-sm btn-info" style="font-size:x-small">Book</button> -->
                            </td>
                        </tr>
                    </table>
                    <h5 class="card-title"></h5>
                    <p class="card-text"></p>
                    <p class="card-text"><small class="text-muted"></small></p>
                    <hr/>                    
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="tab-pane fade" id="Bookings" role="tabpanel" aria-labelledby="Bookings-tab">
            {% for place in my_bookings %}
                <div class="card" style="font-size:small">
                    <div class="card-body">
                    <table class="table table-info" style="font-size:x-small">
                        <tr>
                            <td colspan="1">Approved : </td>
                            <td colspan="2">{{place.approved}}</td>
                            <td colspan="1">Rental Place : </td>
                            <td colspan="2">{{place.listing}}</td>
                            <td colspan="1">Number Of Rooms : </td>
                            <td colspan="2">{{place.number_of_rooms}}</td>
                            
                            <td colspan="1">
                                <form method="post" action="{% url 'rental:pay_booking' %}">
                                    {% csrf_token%}
                                    <input hidden value="{{place.listing.id}}" id="id_rental" name="rental"/>
                                    <input type="submit" value="Pay" />
                                </form>
                                <!-- <button class="btn btn-sm btn-info" style="font-size:x-small">Pay</button> -->
                            </td>
                        </tr>
                    </table>
                    <h5 class="card-title"></h5>
                    <p class="card-text"></p>
                    <p class="card-text"><small class="text-muted"></small></p>
                    <hr/>                    
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="tab-pane fade" id="Payments" role="tabpanel" aria-labelledby="Payments-tab">
        
        
                <div class="card" style="font-size:small">
                    <div class="card-body">
                    <table class="table table-info" style="font-size:x-small">
                        <thead>
                            <tr>
                                <th>Booking</th>
                                <th>Date Of Paymnent </th>
                                <th>Amount Paid</th>
                                <th>POP</th>
                            </tr>
                        </thead>
                        {% for place in my_payments %}
                        <tr>
                            
                            <td >{{place.booking}}</td>
                            <td >{{place.date_of_payment}}</td>
                            <td >{{place.amount}}</td>
                            <td >{{place.proof_of_payment_attached}}</td>
                        </tr>
                        
            {% endfor %}
                    </table>
                    <hr/>                    
                    </div>
                </div>
        </div>
        </div>
    </div>
    
        {% endif%}
    {% endfor %}
   {% endif %}
        {% else %}
        <div class="col-md-10 container ">
            <hr/>
            <a href="{% url 'iauth:edit' %}" class="icon-video popup-vimeo d-flex justify-content-center align-items-center mr-3">
                Update your profile : <span class="fas fa-user"></span>
            </a>
            <hr/>
            <div class="card-deck">
                {% if system_groups %}
                 {% for group in system_groups%}
                     <div class="card" style="font-size:small">
                        <div class="card-body">
                        <h5 class="card-title">{{group.name}}</h5>
                        {% if group.name == "Seeker" %}
                            <p class="card-text">This profile is for students looking for accomodation </p>
                            <p class="card-text"><small class="text-muted"></small></p>
                            <hr/>
                            <form action="{% url 'iauth:edit' %}" method="GET">
                                <input hidden  name="profile" value="{{group.name}}" id="id_profile"/>
                                <input type="submit" class="btn btn-sm btn-primary" style="font-size:x-small" value="I am looking for A Place"/>
                            </form>
                        {% endif %}
                        {% if group.name == "Agent" %}
                            <p class="card-text">This profile is for Personels or organisations who would want to list Placess on behalf of other property Owner</p>
                            <p class="card-text"><small class="text-muted"></small></p>
                            <hr/>
                            <form action="{% url 'iauth:edit' %}" method="GET">
                                <input hidden  name="profile" value="{{group.name}}" id="id_profile"/>
                                <input type="submit" class="btn btn-sm btn-primary" style="font-size:x-small" value="I am an Agent"/>
                            </form>
                        {% endif %}
                        {% if group.name == "Owner" %}
                            <p class="card-text">This profile if for property owners.</p>
                            <p class="card-text"><small class="text-muted"></small></p>
                            <hr/>

                           <form action="{% url 'iauth:edit' %}" method="GET">
                                <input hidden  name="profile" value="{{group.name}}" id="id_profile"/>
                                <input type="submit" class="btn btn-sm btn-primary" style="font-size:x-small" value="I am Property Owner"/>
                            </form>

                        {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}

        </div>
    {% endif %}
   <hr> 
</div>

<script>
var x = document.getElementById("demo");

function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } else { 
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function showPosition(position) {
  x.innerHTML = "Latitude: " + position.coords.latitude + 
  "<br>Longitude: " + position.coords.longitude;
}
</script>
 {% endblock content %}


<html>
<body>

</body>
</html>

iauth/templates/iauth/edit.html
{% extends "base.html" %} {% load bootstrap4 %} {% block title %}Edit{% endblock title %} {% block content %}
<canvas>

</canvas>
<div class="container bg-light">
    <div class="col-md-6">
        <form action="" method="post" class="form">
            {% csrf_token %} 
                {% if system_groups %}
                   You Are Affiliating to the  {{system_groups}}'s group.
                    <input hidden class="form-control" name="my_grp" id="id_my_grp" value="{{system_groups.name}}"/>
                {% endif %}
            {% bootstrap_form form %} 
            {% buttons %}

            <button type="submit" class="btn btn-primary">Submit</button> {% endbuttons %}
        </form>
<hr/>
    </div>
</div>
{% endblock content %}

iauth/templates/iauth/logged_out.html
{% extends "base.html" %} {% block title %}Logged out{% endblock %} {% block content %}
<div class="container col-md-6 bg-light">
    <hr/>
    <hr/>
    <!-- <h1>Logged out</h1> -->
    <h6>
        You have been successfully logged out.
        <hr> You can <a class="text-primary" href="{% url 'iauth:login' %}">log-in again</a>.
    </h6>
    <hr/>

</div>
{% endblock %}

iauth/templates/iauth/password_change_form.html
{% extends "base.html" %} {% load bootstrap4 %} {% block content %}
<canvas></canvas>
<div class="contaner col-md-6">
    <h2>Change Your Password</h2>
    <p>Use the form below to change your Password</p>
    <form action="" method="post" class="form">
        {% csrf_token %} {% bootstrap_form form %} {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button> {% endbuttons %}
    </form>
</div>
{% endblock content %}

iauth/templates/iauth/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
<h2>Password set</h2>
<p>Your password has been set. You can
    <a href="{% url 'authapp:login' %}">log in now</a></p>
{% endblock %}

iauth/templates/iauth/password_reset_confirm.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
{% if validlink %}
<p>Please enter your new password twice:</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" value="Change my password">Submit</button>
    {% endbuttons %}
</form>
{% else %}
<p>The password reset link was invalid, possibly because it has
    already been used. Please request a new password reset.</p>
{% endif %}
{% endblock %}

iauth/templates/iauth/password_reset_done.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
<p>We've emailed you instructions for setting your password.</p>
<p>If you don't receive an email, please make sure you've entered
    the address you registered with.</p>
{% endblock %}

iauth/templates/iauth/password_reset_email.html
Someone asked for password reset for email {{email}}.Follow the Link below {{ protocol }}://{{ domain }}{% url "iauth:password_reset_confirm" uidb64=uid token=token %}

iauth/templates/iauth/password_reset_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Reset your password

{% endblock title %}
{% block content %}
<div class="container">
    <h2>Forgotten your Password</h2>
    <p>Enter your email address to obtain a new password</p>
    <form action="" method="post" class="form ">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary" value="send e-mail">Submit</button>
        {% endbuttons %}
    </form>
</div>
{% endblock content %}

iauth/templates/iauth/profile.html
{% extends "base.html" %} {% block title %}location{% endblock title %} {% block content %}{% load bootstrap4 %}
<script>
$(document).ready(function() {
        var user_id = JSON.parse(document.getElementById('user_id').textContent);
        // alert(user_id)
        $('#id_user_id').val(user_id);
        $('#id_user').val(user_id);
        
        getLocation();

        // var rand = Math.random().toString().substr(2, 8);
        // var d = new Date().getTime();
        // var n = d.toString();
        // setInterval(ajaxCall, 1000); //300000 MS == 5 minutes

        // function ajaxCall() {
        //     //do your AJAX stuff here
        // }
        // setInterval(() => {

        // }, 1000);
    });
</script>
     {{ user.id|json_script:"user_id" }} 
<canvas></canvas>

<!-- <input id="id_user_id"/> -->
<div class="container bg-light">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link " id="groups-tab" data-bs-toggle="tab" data-bs-target="#groups" type="button" role="tab" aria-controls="groups" aria-selected="true">groups</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link active"  id="location-tab" data-bs-toggle="tab" data-bs-target="#location" type="button" role="tab" aria-controls="location" aria-selected="false">location</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="interests-tab" data-bs-toggle="tab" data-bs-target="#interests" type="button" role="tab" aria-controls="interests" aria-selected="false">interests</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade" id="groups" role="tabpanel" aria-labelledby="groups-tab">
       <p>Your groups are listed below</p>

    <hr/>
       {% if groups %} 
    <!-- Welcome : -->
    {% for group in groups %}
    {{group}}
{% endfor%}
{% endif %}
    <hr/>
  </div>
  <div class="tab-pane fade  show active"  id="location" role="tabpanel" aria-labelledby="location-tab">
    <div class="container">
        <table class="table">
            <tr>
                <td>
                    City : {{prof.city}}
                </td>
                <td>Nearby University : {{prof.nearby_institute}}</td>
            </tr>
        </table>
    </div>   
    <p>Update your Current Location</p>
          <form action="" method="post" class="form">
            {% csrf_token %} 
               
            {% bootstrap_form profile_form %} 

            {% buttons %}

            <button type="submit" class="btn btn-primary">Submit</button> {% endbuttons %}
        </form>
    <div hidden class="row no-gutters slider-text js-fullheight align-items-center justify-content-end" data-scrollax-parent="true" style="height: 730px;">
        <div class="col-md-12 ftco-animate mt-5 fadeInUp ftco-animated" data-scrollax=" properties: { translateY: &#39;70%&#39; }" style="transform: translateZ(0px) translateY(36.6685%);">
            <h1 class="mb-4" data-scrollax="properties: { translateY: &#39;30%&#39;, opacity: 1.6 }" style="opacity: 0.9; transform: translateZ(0px) translateY(15.7151%);">location
            </h1>
            <p class="mb-4" data-scrollax="properties: { translateY: &#39;30%&#39;, opacity: 1.6 }" style="opacity: 0.75; transform: translateZ(0px) translateY(15.7151%);">{{welcome}}</p>
            <p class="d-flex align-items-center">
                <!-- <a href="{% url 'iauth:edit' %}" class="btn btn-primary">Edit Your location</a> or
                <a href="{% url 'iauth:password_change' %}" class="btn btn-warning">Change your password</a> -->
                <a href="{% url 'iauth:password_change' %}" class="icon-video popup-vimeo d-flex justify-content-center align-items-center mr-3">
                    <span class="fas fa-lock"></span>
                </a>
                <span class="watch">Change Password</span>
                <!-- <a href="{% url 'iauth:edit' %}" class="icon-video popup-vimeo d-flex justify-content-center align-items-center mr-3">
                    <span class="fas fa-user"></span>
                </a>
                <span class="watch">Edit location</span> -->
            </p>
        </div>
    </div>
    <hr/>
    <hr/>
  </div>
  <div class="tab-pane fade" id="interests" role="tabpanel" aria-labelledby="interests-tab">
      <hr/>
    <hr/>
  </div>
</div>
   
</div>

<hr> 


{% endblock content %}

iauth/templates/iauth/register.html
{% extends "base.html" %} {% load bootstrap4 %} {% block title %}Registration {% endblock title %} {% block content %} {% if form.errors %} {% endif %}
<div class="col-md-12 bg-light">
    <hr/>
    <hr/><br/>
    <div class="col-md-6 bg-light" style="font-size:x-small" >
    <form action="" method="post" class="form container form-group-sm" style="font-size:x-small">
        {% csrf_token %} {% bootstrap_form form %} {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button> {% endbuttons %}
    </form>
    <hr/>
</div>
</div>
{% endblock content %}

iauth/templates/iauth/register_done.html
{% extends "base.html" %} {% block content %}
<h1>Welcome {{ new_user.first_name }}!</h1>
<p>Your account has been successfully created. Now you can <a href="{% url 'iauth:login' %}">log in</a>.</p>
{% endblock content %}