acom/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.contrib import admin
from django.urls import path, include
from .views import login,paynow_payment
urlpatterns = [
    path('admin/', admin.site.urls),
    path('rentals/', include('rental.urls')),
    path('api/login', login),
    path('api/paynow', paynow_payment),
    
    path('', include('iauth.urls')),
    path('rest_api/', include('api.urls')),
]

api/urls.py
from django.conf.urls import url
# from .import views
from .serializers import *
from .views import *
# urlpatterns = [
#     url(r'^$', views.index, name='index'),
# ]
# Routers provide an easy way of automatically determining the URL conf.
app_name = 'api'
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'profiles', ProfileViewSet)
router.register(r'rental_listings', RentalListingViewSet)
router.register(r'bookings', BookingViewSet)
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

rental/urls.py
from django.urls import path

from . import views
app_name = 'rental'
urlpatterns = [
    path('', views.index, name='index'),
    path('places', views.places, name='places'),
    path('add_place', views.add_place, name='add_place'),
    path('search', views.search, name='search'),
    path('place_booking', views.place_booking, name='place_booking'),
    path('my_booking', views.my_booking, name='my_booking'),
    path('pay_booking', views.pay_booking, name='pay_booking'),
    
]

rental/models.py
from django.db import models
from django.db.models.aggregates import Max
from django.db.models.deletion import CASCADE
from django.db.models.fields import BooleanField, DateField, FilePathField, FloatField, IntegerField
from django.contrib.auth.models import User
from api.models import profile
from django_google_maps import fields as map_fields
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'Payments/user_{0}/{1}'.format(filename)

class Rental(models.Model):
    address = map_fields.AddressField(max_length=200)
    geolocation = map_fields.GeoLocationField(max_length=100)
class PaymentMode(models.Model):
    amount = models.FloatField(default=0, null=True)
    url =models.CharField(blank=True ,max_length=500)
    added_on = models.DateTimeField(auto_now=True)

# Create your models here.
class rental_listing(models.Model):
    LISTING_CHOICES = (
        ('App', 'Apartment'),
        ('FH', 'Full House'),
        ('BC', 'Bachelor Court'),
        ('SC', 'spinster Court'),
        ('SH', 'Sharing'),
    )
    City_CHOICES = (
        ('Mutare', 'Mutare'),
        ('Harare', 'Harare'),
        ('Gweru', 'Gweru'),
        ('Masvingo', 'Masvingo'),
        ('Chinhoyi', 'Chinhoyi'),
        ('Bulawayo', 'Bulawayo'),
        ('Zvishavane', 'Zvishavane'),
    )
    PREF_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Mixed', 'Mixed'),
    )
    home_owner= models.ForeignKey(profile ,on_delete=models.CASCADE)
    organization = models.CharField(blank=True ,max_length=200)
    description = models.TextField(blank=True ,max_length=1000)
    lease_terms = models.TextField(blank=True ,max_length=1000)
    type_of_listing = models.CharField(blank=True ,max_length=200 ,choices = LISTING_CHOICES)
    preference = models.CharField(blank=True ,max_length=200 ,choices = PREF_CHOICES)
    address = models.CharField(blank=True ,max_length=200)
    city = models.CharField(blank=True ,max_length=200, choices = City_CHOICES)
    house_number = models.IntegerField(blank=True, null=True)
    max_rooms = models.IntegerField(default=0 ,null=True)
    vacant = models.BooleanField(default=0 ,null=True)
    wifi = models.BooleanField(default=0 ,null=True)
    solar = models.BooleanField(default=0 ,null=True)
    curfew =models.CharField(blank=True ,max_length=200)
    pets_allowed =models.BooleanField(blank=True ,default=0)
    available_rooms = models.IntegerField(default=0 ,null=True)
    price_per_room = models.FloatField(default=0, null=True)
    price_total = models.FloatField(default=0, null=True)
    geom_lat = models.FloatField(default=0 ,null=True)
    geom_long = models.FloatField(default=0 ,null=True)
    added_on = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.address 

class tenant_rental(models.Model):
    tenant= models.ForeignKey(profile ,on_delete=models.CASCADE)
    listing = models.ForeignKey(rental_listing ,on_delete=models.CASCADE)
    staying_period_from = models.DateField(null=True)
    staying_period_to = models.DateField(null=True)
    confirmed = BooleanField(default=0 ,null=True)
    evicted = BooleanField(default=0 ,null=True)
    moved = BooleanField(default=0 ,null=True)
    lease_start_date = DateField(null=True)
    added_on = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.tenant.user.username

class tenant_payment(models.Model):
    LISTING_CHOICES = (
        ('Jan', 'January'),
        ('Feb', 'February'),
        ('Mar', 'March'),
        ('Apr', 'April'),
        ('May', 'May'),
        ('Jun', 'June'),
        ('Jul', 'July'),
        ('Aug', 'August'),
        ('Sep', 'September'),
        ('Oct', 'October'),
        ('Nov', 'November'),
        ('Dec', 'December'),
    )
    listing = models.ForeignKey(tenant_rental ,on_delete=models.CASCADE)
    paid_by= models.ForeignKey(profile ,on_delete=models.CASCADE)
    amount_paid = models.FloatField(default=0 ,null=True)
    balance = models.FloatField(default=0 ,null=True)
    paid_for_month = models.CharField(blank=True ,max_length=200 ,choices = LISTING_CHOICES)
    paid_on = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.paid_by.user.username

class rental_listing_reviews(models.Model):
    reviewed_by= models.ForeignKey(profile ,on_delete=models.CASCADE)
    listing = models.ForeignKey(rental_listing ,on_delete=models.CASCADE)
    rating = models.IntegerField(default=0 ,null=True)
    comment = models.IntegerField(default=0 ,null=True)
    added_on = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.reviewed_by.user.username

class Search(models.Model):
    address= models.CharField(blank=True ,max_length=200 ,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.address

class Booking(models.Model):
    tenant= models.ForeignKey(profile ,on_delete=models.CASCADE)
    listing = models.ForeignKey(rental_listing ,on_delete=models.CASCADE)
    number_of_rooms = models.IntegerField(default=0 ,null=True)
    approved = BooleanField(default=0 ,null=True)
    rejected = BooleanField(default=0 ,null=True)
    waiting_list = BooleanField(default=0 ,null=True)
    date_of_booking = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.tenant.user.username

class BookingPay(models.Model):
    payment_made_by= models.ForeignKey(User ,on_delete=models.CASCADE)
    booking= models.ForeignKey(Booking ,on_delete=models.CASCADE)
    proof_of_payment_attached = BooleanField(default=0 ,null=True)
    # file = models.FileField(upload_to=user_directory_path ,null=True)
    amount = models.FloatField(null=True)
    date_of_payment = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.booking.tenant.user.username

rental/views.py
from django.shortcuts import render ,redirect

# Create your views here.
from django.http import HttpResponse
from .models import *
from .tables import *
from .filters import *
from django_tables2.config import RequestConfig
from rest_framework.views import APIView
from . tables import *
from django_tables2.export.export import TableExport
# import requests
import json
import http.client
import json
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django_tables2.export.export import TableExport
import folium
import geocoder
from .forms import *
def index(request):
    form = SearchForm()
    # prof = profile.objects.get(user=request.user)
    prof = profile.objects.get(user=request.user)
    if prof:
        rental_places = rental_listing.objects.filter(city=prof.city,preference=prof.gender)
    else:
        rental_places = rental_listing.objects.all()
    m = folium.Map(location=[-17.3708521,30.1473976] , zoom_start=13)
    for place in rental_places:
        # folium.Marker([-17.845634, 31.119771] , tooltip="Click for More",popup="Harare").add_to(m)
        # folium.Marker([-17.351682718824286, 30.205762433872952] , tooltip="Click for More",popup="Chinhoyi").add_to(m)
        folium.Marker([place.geom_lat,place.geom_long] , tooltip=place.description,popup=str(place.available_rooms)+ " , $"+ str(place.price_per_room)).add_to(m)
    m = m._repr_html_()
    booking_form = BookingForm()
    context = {
        'form':form,
        'booking_form':booking_form,
        'm':m,
        'rental_places': rental_places,
    }
    # return HttpResponse("Rental Places")
    return render(request, 'rental/index.html', context)

def search(request):
    # address = request.POST.get('address')
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/rentals/search')
    else:
        form = SearchForm()
    address = Search.objects.all().last()
    location = geocoder.osm(address)
    lat = location.lat
    lng = location.lng
    country = location.country
    print(lat)
    print(lng)
    if lat == None or lng == None or country==None:
        address.delete()
        address = Search.objects.all().last()
        location = geocoder.osm(address)
        lat = location.lat
        lng = location.lng
        country = location.country
    rental_places = rental_listing.objects.filter(city=address.address)
    
    m = folium.Map(location=[-17.3708521,30.1473976] , zoom_start=13)
    # folium.Marker([-17.845634, 31.119771] , tooltip="Click for More",popup="Harare").add_to(m)
    # folium.Marker([-17.351682718824286, 30.205762433872952] , tooltip="Click for More",popup="Chinhoyi").add_to(m)
    folium.Marker([lat,lng] , tooltip="Click for More",popup=country + " , "+ address.address).add_to(m)
    for place in rental_places:
        # folium.Marker([-17.845634, 31.119771] , tooltip="Click for More",popup="Harare").add_to(m)
        # folium.Marker([-17.351682718824286, 30.205762433872952] , tooltip="Click for More",popup="Chinhoyi").add_to(m)
        folium.Marker([place.geom_lat,place.geom_long] , tooltip=place.description,popup=str(place.available_rooms)+ " , $"+ str(place.price_per_room)).add_to(m)
    m = m._repr_html_()
    context = {
        'form':form,
        'm':m,
        'rental_places': rental_places,
    }
    # return HttpResponse("Rental Places")
    return render(request, 'rental/search.html', context)

def places(request):
    prof = profile.objects.get(user=request.user)
    if prof:
        rental_places = rental_listing.objects.filter(city=prof.city)
    else:
        rental_places = rental_listing.objects.all()
    groups = request.user.groups.all()
    
    myFilter = RentalListingFilter(request.GET,queryset=rental_places)
    rental_places = myFilter.qs
    rental_places_table = RentalListingTable(rental_places)
    RequestConfig(request).configure(rental_places_table)
    export_format = request.GET.get("_export", None)
    if TableExport.is_valid_format(export_format):
        exporter = TableExport(export_format, rental_places_table)
        return exporter.response("table.{}".format(export_format))
    return render(request, 'rental/list.html', {'rental_places': rental_places ,'myFilter':myFilter, 'rental_places_table': rental_places_table})

def add_place(request):
    if request.method == 'POST':
        form = RentalPlaceForm(request.POST)
        if form.is_valid():
            form.save()
            rental_places = rental_listing.objects.all()
            lat = request.POST.get('geom_lat')
            lng = request.POST.get('geom_long')
            organization = request.POST.get('organization')
            address = request.POST.get('address')
            m = folium.Map(location=[-17,32] , zoom_start=10)
            folium.Marker([lat,lng] , tooltip="Click for More",popup=organization + " , "+ address).add_to(m)
            m = m._repr_html_()
            context = {
                'form':form,
                'm':m,
                'rental_places': rental_places,
            }
            # return HttpResponse("Rental Places")
            return render(request, 'rental/index.html', context)
    else:
        form = RentalPlaceForm()
    # rental_places = rental_listing.objects.all()
    # m = folium.Map(location=[-17,31] , zoom_start=6)
    # for place in rental_places:
    #     # folium.Marker([-17.845634, 31.119771] , tooltip="Click for More",popup="Harare").add_to(m)
    #     # folium.Marker([-17.351682718824286, 30.205762433872952] , tooltip="Click for More",popup="Chinhoyi").add_to(m)
    #     folium.Marker([place.geom_lat,place.geom_long] , tooltip=place.description,popup=str(place.available_rooms)+ " , $"+ str(place.price_per_room)).add_to(m)
    # m = m._repr_html_()
    context = {
        'form':form,
        # 'm':m,
        # 'rental_places': rental_places,
    }
    # return HttpResponse("Rental Places")
    return render(request, 'rental/add_place.html', context)

    # https://www.paynow.co.zw/Payment/BillPaymentLink/?q=aWQ9MTMwOTYmYW1vdW50PTUwLjAwJmFtb3VudF9xdWFudGl0eT0wLjAwJmw9MQ%3d%3d


def place_booking(request):
    if request.POST:
        user_id = request.POST.get('user_id')
        place_id = request.POST.get('listing')
        rooms = request.POST.get('number_of_rooms')
        rentallisting = rental_listing.objects.get(id=place_id)
        user_profile = profile.objects.get(user=user_id)
        data = {
            'tenant': user_profile,
            'listing': rentallisting,
            'number_of_rooms': rooms
        }
        bform = BookingForm(data=data)
        if bform.is_valid():
            bform.save()
            return redirect('/')
        # b4_Form = Booking.objects.get(user=request.user)
        # b4_Form.city = request.POST.get('city')
        # b4_Form.nearby_institute = request.POST.get('nearby_institute')
        # b4_Form.save() 
    context = {
    }
    return render(request, 'rental/add_place.html', context)
def pay_booking(request):
    error_message = ""
    success_message = ""
    if request.POST:
        form = BookingPayForm(request.POST)
        bng = request.POST.get('booking')
        booking_listing = Booking.objects.get(id=bng)
        lsng = booking_listing.listing
        print('lsng')
        print(lsng.id)
        if form.is_valid():
            form.save()
            b4_Form = rental_listing.objects.get(id=lsng.id)
            print(b4_Form)
            print('b4_Form.available_rooms - 1')
            print(b4_Form.available_rooms - 1)
            b4_Form.available_rooms = b4_Form.available_rooms - 1
            if b4_Form.save():
                my_profile = profile.objects.get(user=request.user.id)
                my_bookings = Booking.objects.filter(tenant=my_profile)
                print(my_bookings)
                
                myFilter = BookingFilter(request.GET,queryset=my_bookings)
                my_bookings = myFilter.qs
                bookings_table = BookingTable(my_bookings)
                RequestConfig(request).configure(bookings_table)
                export_format = request.GET.get("_export", None)
                if TableExport.is_valid_format(export_format):
                    exporter = TableExport(export_format, bookings_table)
                    return exporter.response("table.{}".format(export_format))
                context = {
                    "bookings_table":bookings_table,
                    "my_bookings": my_bookings,
                    "myFilter": myFilter,
                    "my_profile":my_profile,
                }
                return render(request, 'rental/my_bookings.html', context)
            else:
                error_message = "Data Not Saved"
            
    else:
        form = BookingPayForm()
    context = {
        "form":form,
        "error_message": error_message,
    }
    return render(request, 'rental/pay.html', context)
def my_booking(request):
    my_profile = profile.objects.get(user=request.user.id)
    my_bookings = Booking.objects.filter(tenant=my_profile)
    print(my_bookings)
    
    myFilter = BookingFilter(request.GET,queryset=my_bookings)
    my_bookings = myFilter.qs
    bookings_table = BookingTable(my_bookings)
    RequestConfig(request).configure(bookings_table)
    export_format = request.GET.get("_export", None)
    if TableExport.is_valid_format(export_format):
        exporter = TableExport(export_format, bookings_table)
        return exporter.response("table.{}".format(export_format))
    context = {
        "bookings_table":bookings_table,
        "my_bookings": my_bookings,
        "myFilter": myFilter,
        "my_profile":my_profile,
    }
    return render(request, 'rental/my_bookings.html', context)

rental/templates/rental/add_place.html
 <!DOCTYPE html>{% extends "base.html" %} {% block title %}Dashboard{% endblock title %} {% block content %}
 {% load crispy_forms_tags %} 
 <script>
$(document).ready(function() {
        var user_id = JSON.parse(document.getElementById('user_id').textContent);
        // alert(user_id)
        $('#id_user_id').val(user_id);
        $('#id_home_owner').val(user_id);
        
        getLocation();

        // var rand = Math.random().toString().substr(2, 8);
        // var d = new Date().getTime();
        // var n = d.toString();
        // setInterval(ajaxCall, 1000); //300000 MS == 5 minutes

        // function ajaxCall() {
        //     //do your AJAX stuff here
        // }
        // setInterval(() => {

        // }, 1000);
    });
</script>
 <div class="container bg-light"> 
     {{ user.id|json_script:"user_id" }} 
      <hr/>
      <hr/>
      <hr/>
      <hr/>
      <hr/>
      <button onclick="getLocation()">Add this Current Location</button>
        <p id="demo"></p>
      <hr/>
        <div class="container">
           {% csrf_token%}
           <!-- {{form.as_p}} -->
           <!-- <input id="id_user_id"/>
           <input id="id_lat"/>
           <input id="id_long"/> -->
           {% crispy form form.helper %}
           <!-- <input type="search" placeholder="search" name="address" id="id_address" aria-label="search"/> -->
           <!-- <input type="submit" value="Submit" /> -->
        </div>
  </div>
<script>
var x = document.getElementById("demo");

function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } else { 
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function showPosition(position) {
//   x.innerHTML = "Latitude: " + position.coords.latitude + 
//   "<br>Longitude: " + position.coords.longitude;
        $('#id_geom_lat').val(position.coords.latitude);
        $('#id_geom_long').val(position.coords.longitude);

}
</script>
 {% endblock content %}

rental/templates/rental/index.html
{% extends "base.html" %} {% block title %}Rental Listings{% endblock title %} {% block content %} {% load static %}
<div class="container bg-light">
    <!-- <canvas></canvas> -->
    <hr/>
    <hr/>
    <hr/>
    <hr/>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#map" type="button" role="tab" aria-controls="map" aria-selected="true">map</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="table-tab" data-bs-toggle="tab" data-bs-target="#table" type="button" role="tab" aria-controls="table" aria-selected="false">table</button>
        </li>

    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="map" role="tabpanel" aria-labelledby="map-tab">
            <hr/>
            <div class="col-md-12" height="100">
                <form method="post" action="{% url 'rental:search' %}">
                    {% csrf_token%} {{form}}
                    <!-- <input type="search" placeholder="search" name="address" id="id_address" aria-label="search"/> -->
                    <input type="submit" value="Submit" />
                </form>
                {{m|safe}}
            </div>
        </div>
        <div class="tab-pane fade" id="table" role="tabpanel" aria-labelledby="table-tab">
            <hr/> {% if rental_places %}
            <div class="container">
                <div class="row">
                    {% for rental in rental_places%}
                    <div class="card col-md-4">
                        <table class="table">
                            <tr>
                                <td colspan="2"> <img class="card-img-top" src="{% static 'iauth/content/img/hmfl.png' %}" style="width:50%;height:50%;" alt="Card image cap">
                                </td>
                                <td colspan="10" style="font-size:x-small">
                                    <p class="">Max Rooms: <i class="text-success">{{rental.max_rooms}}</i></p>
                                    <p class="">Available Rooms: <i class="text-success">{{rental.available_rooms}}</i></p>
                                </td>
                            </tr>
                        </table>
                        <div class="card-body">
                            <table class="table">
                                <tbody style="font-size:x-small">
                                    <tr>
                                        <td>
                                            Type
                                        </td>
                                        <td>
                                            {{rental.type_of_listing}}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Details
                                        </td>
                                        <td>
                                            {{rental.description}}

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Price
                                        </td>
                                        <td>
                                            ${{rental.price_per_room }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Address
                                        </td>
                                        <td>
                                            No: {{rental.house_number }} - {{rental.address }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            City
                                        </td>
                                        <td>
                                            {{rental.city }}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="container">
                            <!-- <small class="text-muted">{{rental.added_on}}</small> -->
                            <!-- <hr/> -->
                            <div class="row" style>
                                <button class="btn btn-info btn-sm col-md-4" style="font-size:x-small">View Details</button>
                                <form method="post" action="{% url 'rental:place_booking' %}">
                                    {% csrf_token%}
                                     <input name="number_of_rooms" placeholder="Number Of Rooms" required="true" type="number" id="id_number_of_rooms" value=""/>

                                     <input hidden name="listing" type="number" required="" id="id_listing" value="{{rental.id }}"/>
                                     <input hidden name="user_id" type="number" required="" id="id_user_id" value="{{request.user.id }}" />
                                    
                                    <input class="btn btn-info btn-sm col-md-4" style="font-size:x-small" type="submit" value="Book" />
                                </form>
                                
                                <button class="btn btn-info btn-sm col-md-4" style="font-size:x-small">Contact Owner</button>
                            </div>
                            <hr/>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <br/> {% endif %}
        </div>
    </div>
</div>


<hr> {% endblock content %}

rental/templates/rental/list.html
{% extends "base.html" %} {% block title %}Rental Listings{% endblock title %} {% block content %}
{% load render_table from django_tables2 %}
{% load static %}
<div class="container bg-light" >
   <!-- <canvas></canvas> -->
   <hr/>
   <hr/>
   <hr/>
   <hr/>
   
<form class="form-inline" action="" method="get" style="font-size:xx-small"> 
    <table class="table table-striped">
        <tr class="bg-dark text-light">
            {% for field in myFilter.form %}
            <td class="text-left" style="text-align: start;" colspan="2">
                {{field.label_tag}} 
            </td>
            {% endfor %}
            <td colspan="2"></td>
        </tr>
        <tr>{% for field in myFilter.form %}
            <td colspan="2">
                 {{field}}

            </td>
            {% endfor %}
            <td colspan="2"> <button class="btn btn-sm btn-outline-success" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>ic_find_in_page_24px</title>
                <g fill="#020202">
                    <path d="M20 19.59V8l-6-6H6c-1.1 0-1.99.9-1.99 2L4 20c0 1.1.89 2 1.99 2H18c.45 0 .85-.15 1.19-.4l-4.43-4.43c-.8.52-1.74.83-2.76.83-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5c0 1.02-.31 1.96-.83 2.75L20 19.59zM9 13c0 1.66 1.34 3 3 3s3-1.34 3-3-1.34-3-3-3-3 1.34-3 3z"></path>
                </g>
            </svg></button></td>
        </tr>
    </table>
    
  <!-- {{myFilter.form.as_p}} -->

</form>
   <div class="table table-striped" style="font-size:x-small">
    {%if rental_places %} 
        {% render_table rental_places_table %}
    {% endif %}
</div>
</div>
<hr> {% endblock content %}

rental/templates/rental/pay.html
{% extends "base.html" %} {% block title %} {% load bootstrap4 %}Pay Booking{% endblock title %} {% block content %} {% load static %}
<div class="container bg-light">
    <!-- <canvas></canvas> -->
    <hr/>
    <hr/>
    <hr/>
    <hr/>
    <div class="container">
        <form method="post" action="{% url 'rental:pay_booking' %}">
            {% csrf_token%} 
            {% bootstrap_form form %} 
            <!-- <input type="search" placeholder="search" name="address" id="id_address" aria-label="search"/> -->
            <input type="submit" value="Submit" />
        </form>
        <hr/>
    </div>
</div>


<hr> {% endblock content %}

rental/templates/rental/search.html
{% extends "base.html" %} {% block title %}Rental Listings{% endblock title %} {% block content %}
{% load static %}
<div class="container bg-light" >
   <!-- <canvas></canvas> -->
   <hr/>
   <hr/>
   <hr/>
   <hr/>
   <div class="col-md-10">
       <form method="post" action="{% url 'rental:search' %}">
           {% csrf_token%}
           {{form}}
           <!-- <input type="search" placeholder="search" name="address" id="id_address" aria-label="search"/> -->
           <input type="submit" value="Submit" />
       </form>
       {{m|safe}}
   </div>
   {% if rental_places %}
    <div class="container" hidden>
            <div class="row">
    {% for rental in rental_places%}
                <div class="card col-md-4">
                   <table class="table">
                       <tr>
                           <td colspan="2"> <img class="card-img-top" src="{% static 'iauth/content/img/hmfl.png' %}" style="width:50%;height:50%;" alt="Card image cap">
                    </td><td colspan="10" style="font-size:x-small">
                    <p class="">Max Rooms: <i class="text-success">{{rental.max_rooms}}</i></p>
                    <p class="">Available Rooms: <i class="text-success">{{rental.available_rooms}}</i></p>
                    </td>
                    </tr>
                   </table>
                    <div class="card-body">
                    <table class="table">
                       <tbody style="font-size:x-small">
                            <tr>
                            <td>
                               Type
                            </td>
                            <td>
                               {{rental.type_of_listing}}
                            </td>
                        </tr>
                         <tr>
                            <td>
                               Details
                            </td>
                            <td>
                                {{rental.description}}

                            </td>
                        </tr>
                        <tr>
                            <td>
                               Price
                            </td>
                            <td>
                                ${{rental.price_per_room }}
                            </td>
                        </tr>
                         <tr>
                            <td>
                               Address
                            </td>
                            <td>
                                No: {{rental.house_number }} - 
                                {{rental.address }}
                            </td>
                        </tr>
                         <tr>
                            <td>
                               City
                            </td>
                            <td>
                                {{rental.city }}
                            </td>
                        </tr>
                       </tbody>
                    </table>
                    </div>
                    <div class="container">
                    <!-- <small class="text-muted">{{rental.added_on}}</small> -->
                    <!-- <hr/> -->
                   <div class="row" style> 
                        <button class="btn btn-info btn-sm col-md-4" style="font-size:x-small" >View Details</button>
                        <button class="btn btn-success btn-sm col-md-4" style="font-size:x-small">Book</button>
                        <button class="btn btn-info btn-sm col-md-4" style="font-size:x-small">Contact Owner</button>
                   </div>
                   <hr/>
                    </div>
                </div>
        {% endfor %}
        </div>
    </div>
    <br/>
    {% endif %}
</div>
<hr> {% endblock content %}